travis:
  secure:
    BINSTAR_TOKEN: Tly5H1KtPBDOgpv1PC7DBuiK7F4JB8ZqWqUR2XrUnEktZuX0meyDpFLEWqFUwOhwap6Ak1Dd+7fswAQA9oF22yuN+nAAtVuIAtms4QppxNGO+Dh53Jn6yk/lMN7OGsf8lhHTIlqpW1FLpPLEvZrQlj/MCs+Y/6/GcIouvpz9L1ZgipxUbVXcWQ00DBbs0jKeKLqYbhsqIg9EkBGQuR1QAWMAdzoKIrcOtiFVJSDII24Jdja28dg/1hOz+iXPMlFx1Ddbd6KicUHvjshj3G7QGRHoQVBc2R4KFq+gE6Q6V2yEkh3M/6SqG0qfdgp6l5blHkzMjG5vpEpsQiPG1SVtlxvTOk300RPeBYqSmReShJFVzGLue00Pwbzwusd7V4h5s8VTdJNUj0hWBtyyhhJPnZcdX3hT6bf8Hg6JLdx0j3W9N8RPtCPhOD84/YMJb503mnPnWbzmuR6VvKpjfMM4pegLn9Rvv3h4KQqoh+BAb8MUeEhdGmqVok+Z1DtOGWGxwMwHtrja5gq8O1APoolDcNO2dkET2Msn6W3f+1W388B4GxDlaKh5YGtIkZfERp7ntxKwlJ7d+pp88NVPrHH+pc5b11cCTfuPsMIJFkMwB9rgao53iKoRPLcqx9qeasD+/CpwA62xrBL/hh4+dU4sRe+j1h9GE7O+QWw99gysotg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
