travis:
  secure:
    BINSTAR_TOKEN: ELETjRXUJ7pNhTYod8FP1rtsw7gs4RfX9C89rRQ1shujD6Np3FLrOtFUTHuMLs7nfia/oqeQ7sTbnRC8c1xsOGN9aA0F4ymuQb90S50xX0wdYLjC6kKUAcIzEMXNXiUGX0O0asi7Hv0q2zMJPpLwDXwWFDPmld94FYTE1HjCbb03bhmvORN7J3XiNRHao4vFPZOihmutwt0HhmyyjSpM1Vva5kkmT6wx1Qad2usTvUQVMJPnXCmNxloWbxEP14laG7hOfeMhFH2JN61lXqsvTCOBj8eAuLLM/UJfnjGooPX7W02eNr09pzpl+ko7ENGhWz6cTyJvGRf4n8zwbfQy4ra7IddxqcLPVaAaPzo+d79cjhMIq9wbtjKhAMd6TPA7LUNWcWj2NA9ECFuuJzal2ZU6AtcAxcgAEB0VFbeRZeFMj+HaiDslmGpQOVSPH/FYV1X3+KVHeATncoaRXE7hXpVSRnh82aNwRJZWuj+9UqjsUWi8DbxR17RC1IcGwQi83kRtZFDm1wEaeCZ3PI3mBPvJiZcNwWlv713tiWJcnAc0eaO/RcfrzuRDLeTfwEXhLbfPfxHSNO++ra2w3wFy1xduy+aZhGPq7dZHO3ZWXVwZ+Hp1L+Ffky/NsLCFHHW5OwUDyYkGpNyhLH/ygMCfvefvcdivf/lqSX+OGt5cHTs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
